### PR TITLE
[ja] improve linkage, sound, translation, pos sections code

### PR DESCRIPTION
**Pull request by xxyzz**
Please notice I changed the wikitext link regex in the last commit to match file links in ja edition.

### CODE REVIEW

**Comment by kristian-clausal** [comment]
Using `\w\d` is obviously better, in retrospect, for that. We don't live in the ASCII ages anymore.

**Comment by xxyzz** [comment]
Failed? How?

**Comment by kristian-clausal** [comment]
Wikitextprocessor?

**Comment by xxyzz** [comment]
I think the compiled regex pattern is cached with another edition's namespace data from other tests.

**Pull request merged**
