### PR TITLE
Improving the German, Spanish and Russian extractors

### PR DESCRIPTION
**Pull request by empiriker**
Hi there!

This will probably be my last bigger PR in a while. 

The last item on my list was to check how well the new extractors perform when extracting Latin and Ancient Greek data. This PR addresses a bunch of issues/improvements I noted in the process.

Let me know if you prefer that I rather add these in separate PRs.

### CODE REVIEW

**Comment by 999pingGG** [comment]
I was coincidentially wondering how should I approach extracting Spanish "forma verbal" sections since I see a lot of words reporting "Unprocessed section: forma verbal"

**Comment by xxyzz** [comment]
Thanks for your contribution!

**Comment by empiriker** [comment]
Thanks for the review and quick acceptance of my PR! 

As mentioned, I achieved what I set out to do and will be a less active contributor from here on out. I will keep an eye on the developments and see if any problem with my code occur. Please feel free to tag me whenever. 

Finally, I want to say that it was a pleasure contributing and collaborating. Thanks for all the help and encouragement along the way!

**Comment by kristian-clausal** [comment]
Thank you for your contributions! It was great to have you working with us, good luck with future projects.

**Pull request merged**
